# Generated by Django 3.2.16 on 2022-12-06 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='full_name',
            new_name='employee_name',
        ),
    ]
